E3245/HeliosHighlander

XComGame/Classes/X2DialogueTagTemplate.uc

X2DialogueTagTemplate fixes for custom Strategy Presentation layer

---

XComGame/Classes/X2StatusEffects.uc

Fix for recovered Unconscious units would stay ragdolled and have messed up behavior

---

HeliosHighlander/Config/XComGame.ini
XComGame/Classes/UITacticalTimeline.uc

Added ability for effects to mask unit from Timeline

---

HeliosHighlander/Config/XComGame.ini
HeliosHighlander/Config/XComGameCore.ini
XComGame/Classes/X2Effect_ApplyWeaponDamage.uc

Allow Dark Events to enable `ExplosiveFalloff` for any explosives

---

HeliosHighlander/Config/XComGame.ini
HeliosHighlander/Config/XComGameCore.ini
XComGame/Classes/HSHelpers.uc
XComGame/Classes/X2Effect_ApplyWeaponDamage.uc

`CheckTacticalTags()` function for `HSHelpers.uc`

---

XComGame/Classes/UIUnitFlag.uc

Bugfix: Compile error at 160

---

XComGame/Classes/XComGameState_HeadquartersDio.uc

Allow Event Listeners to open/close the Alt Market during OnTurnUpkeep

---

HeliosHighlander/Classes/UISL_Shell_Helios.uc
HeliosHighlander/Config/XComGame.ini

Added UISL that prints the Version Text onto Shell Screen

---

XComGame/Classes/X2Effect_ApplyWeaponDamage.uc

Added event trigger for `CalculateCoverMitigationForAbility()`

---

HeliosHighlander/Config/XComUI.ini
XComGame/Classes/UIUnitFlag.uc

Fixed alignment issue. #15 now uses a Tuple that is sent on Init

---

XComGame/Classes/XComIdleAnimationStateMachine.uc

I've noticed some weird oddities with the new Idle State machine changes while breaching (Verge losing his animations entirely, agents not facing their targets during the breach sequence, etc.). This PR reverts those changes until we can fix it up.
Closes #5

Reverted changes from WotC CHL #269

---

XComGame/Classes/X2AbilityTag.uc
XComGame/Classes/X2DownloadableContentInfo.uc

Implemented AbilityTagExpandHandler_CH()

---

XComGame/Classes/UIUnitFlag.uc

Fixed bOnlyShowMaxHealth set to true, preventing any HP updates

---

HeliosHighlander/Classes/X2DownloadableContentInfo_Helios_Overhaul.uc
HeliosHighlander/Config/XComGame.ini
XComGame/Classes/HSHelpers.uc
XComGame/Classes/XComParcelManager.uc

Implemented friendlier way of adding Markup Maps to existing maps

---

XComGame/Classes/XComStrategySoundManager.uc
XComGame/Classes/XComTacticalSoundManager.uc

Un-privates most functions in the Sound Manager classes

---

XComGame/Classes/XComGameState_Unit.uc

Implemented OverrideDamageRemovesReserveActionPoints event trigger

---

XComGame/Classes/HSHelpers.uc
XComGame/Classes/X2Effect_ApplyWeaponDamage.uc

The previous one didn't work due to the value being modified too late, so we're resorting to a delegate instead.
Closes #50

Cover Mitigation changes

---

XComGame/Classes/HSHelpers.uc
XComGame/Classes/HSTacticalVisualizationTemplate.uc
XComGame/Classes/XComGameStateContext_TacticalGameRule.uc

Visualizer Templates for `XCGS_TacticalGameRule`

---

XComGame/Classes/X2StrategyGameRulesetDataStructures.uc

Added new enum for strategy notifications

---

XComGame/Classes/XComGameState_AIReinforcementSpawner.uc

Added event trigger in `InitiateReinforcements()`

---

XComGame/Classes/XComGameState_Effect.uc

Fix infinite effects not cleansing after Tactical end on XCom units

---

XComGame/Classes/XComGameState_Unit.uc

Added event trigger and tuple for ProgressScars

---

XComGame/Classes/XComGameStateContext_Ability.uc

Added `PostModifyNewAbilityContext` feature from WotC CHL #890

---

XComGame/Classes/SeqAct_PutItemInGameObject.uc

ContainedItems support for `SeqAct_PlaceItemInGameObject`

---

XComGame/Classes/X2DioStrategyActionTemplate.uc

Un-privated all functions and vars in `X2DioStrategyActionTemplate.uc`
